import type { AbilityDef, ClassId } from './types';

/** Every class gets the same evade: a quick backstep (or a roll through when cornered). */
export const EVADE: AbilityDef = {
  id: 'evade', name: 'Evade', slot: 'evade', kind: 'dash',
  range: 0, cost: 0, cooldown: 3.6,
  windup: 0.03, active: 0.26, recovery: 0.14,
  power: 0, damageType: 'physical',
  dash: { distance: 2.8, iframes: 0.3 },
  anim: 'evade',
  desc: 'Quick backstep with invulnerability. Rolls through the enemy when cornered.',
};

export const CLASS_ABILITIES: Record<ClassId, AbilityDef[]> = {
  vanguard: [
    {
      id: 'slash', name: 'Slash', slot: 'basic', kind: 'melee',
      range: 1.95, cost: 0, cooldown: 0.15,
      windup: 0.22, active: 0.1, recovery: 0.3,
      power: 1.0, damageType: 'physical', stagger: 0.22, knockback: 1.2, lunge: 0.3,
      anim: 'slash', desc: 'Reliable sword cut.',
    },
    {
      id: 'shield_bash', name: 'Shield Bash', slot: 'skill', kind: 'melee',
      range: 1.7, cost: 10, cooldown: 7,
      windup: 0.2, active: 0.1, recovery: 0.38,
      power: 0.6, damageType: 'physical', stun: 0.9, knockback: 4.5, lunge: 0.5,
      anim: 'bash', desc: 'Fast bash that stuns.',
    },
    {
      id: 'rising_cleave', name: 'Rising Cleave', slot: 'skill', kind: 'melee',
      range: 2.25, cost: 15, cooldown: 6,
      windup: 0.58, active: 0.14, recovery: 0.48,
      power: 2.3, damageType: 'physical', heavy: true, knockback: 8, lunge: 0.9, stagger: 0.5,
      anim: 'overhead', desc: 'Telegraphed heavy cleave with big knockback.',
    },
    {
      id: 'bulwark', name: 'Bulwark', slot: 'defense', kind: 'guard',
      range: 0, cost: 0, cooldown: 4,
      windup: 0.05, active: 1.1, recovery: 0.2,
      power: 0, damageType: 'physical',
      guard: { reduction: 0.8, parryWindow: 0.22, reflectProjectiles: true },
      anim: 'guard', desc: 'Raise the shield. Perfect timing parries and reflects projectiles.',
    },
    {
      id: 'judgment', name: 'Judgment', slot: 'ultimate', kind: 'aoe',
      range: 2.7, cost: 100, cooldown: 10,
      windup: 0.55, active: 0.18, recovery: 0.7,
      power: 4.0, damageType: 'physical', heavy: true, unblockable: true, knockback: 10, lunge: 2.2,
      airborne: true, stun: 0.6,
      anim: 'leap', desc: 'Leaping holy slam. Unblockable.',
    },
  ],
  ronin: [
    {
      id: 'swift_cut', name: 'Swift Cut', slot: 'basic', kind: 'melee',
      range: 1.85, cost: 0, cooldown: 0.1,
      windup: 0.15, active: 0.08, recovery: 0.22,
      power: 0.72, damageType: 'physical', stagger: 0.18, knockback: 0.8, lunge: 0.35,
      anim: 'slash', desc: 'Lightning-fast katana cut.',
    },
    {
      id: 'iaido', name: 'Iaido Dash', slot: 'skill', kind: 'dash',
      range: 4.4, cost: 15, cooldown: 6,
      windup: 0.3, active: 0.18, recovery: 0.32,
      power: 1.8, damageType: 'physical', heavy: true,
      dash: { distance: 5.2, through: true, iframes: 0.18, strike: true },
      stagger: 0.4,
      anim: 'dash', desc: 'Dash straight through the enemy with a drawn cut.',
    },
    {
      id: 'crescent', name: 'Crescent Wave', slot: 'skill', kind: 'projectile',
      range: 10, cost: 10, cooldown: 5,
      windup: 0.24, active: 0.06, recovery: 0.3,
      power: 1.05, damageType: 'physical',
      projectile: { speed: 15, radius: 0.5, style: 'wave' }, stagger: 0.2,
      anim: 'spin', desc: 'Throws a blade of wind.',
    },
    {
      id: 'counter', name: 'Counter Stance', slot: 'defense', kind: 'guard',
      range: 0, cost: 0, cooldown: 5,
      windup: 0.04, active: 0.75, recovery: 0.28,
      power: 0, damageType: 'physical',
      guard: { reduction: 0.35, parryWindow: 0.45, counterPower: 2.1 },
      anim: 'counter', desc: 'Wide parry window; a parry triggers an instant riposte.',
    },
    {
      id: 'thousand_cuts', name: 'Thousand Cuts', slot: 'ultimate', kind: 'melee',
      range: 2.6, cost: 100, cooldown: 10,
      windup: 0.3, active: 0.95, recovery: 0.5,
      power: 0.58, damageType: 'physical', hits: 8, lunge: 1.4, stagger: 0.25, knockback: 0.5,
      heavy: true, hyperArmor: true,
      anim: 'flurry', desc: 'Eight-hit flurry with hyper armor.',
    },
  ],
  arcanist: [
    {
      id: 'arcane_bolt', name: 'Arcane Bolt', slot: 'basic', kind: 'projectile',
      range: 11, cost: 0, cooldown: 0.35,
      windup: 0.28, active: 0.05, recovery: 0.28,
      power: 0.82, damageType: 'magic', stagger: 0.15,
      projectile: { speed: 17, radius: 0.32, style: 'arcane' },
      anim: 'cast', desc: 'Quick arcane missile.',
    },
    {
      id: 'frost_nova', name: 'Frost Nova', slot: 'skill', kind: 'aoe',
      range: 2.5, cost: 15, cooldown: 7,
      windup: 0.3, active: 0.1, recovery: 0.36,
      power: 0.8, damageType: 'magic', knockback: 7,
      applies: [{ status: 'chill', duration: 3, stacks: 2 }],
      anim: 'castBig', desc: 'Burst of frost around you. Chills and repels.',
    },
    {
      id: 'hex_orb', name: 'Hex Orb', slot: 'skill', kind: 'projectile',
      range: 11, cost: 20, cooldown: 8,
      windup: 0.4, active: 0.05, recovery: 0.32,
      power: 1.3, damageType: 'magic', stagger: 0.3,
      applies: [{ status: 'mark', duration: 4 }, { status: 'burn', duration: 3, stacks: 2 }],
      projectile: { speed: 8, radius: 0.55, style: 'hex' },
      anim: 'cast', desc: 'Slow cursed orb: marks (+15% damage taken) and burns.',
    },
    {
      id: 'blink', name: 'Blink', slot: 'defense', kind: 'blink',
      range: 0, cost: 0, cooldown: 6,
      windup: 0.04, active: 0.08, recovery: 0.16,
      power: 0, damageType: 'magic', iframes: 0.25,
      dash: { distance: 4.6, iframes: 0.25 },
      anim: 'blink', desc: 'Teleport away. When cornered, blinks behind the enemy.',
    },
    {
      id: 'meteor', name: 'Meteor', slot: 'ultimate', kind: 'meteor',
      range: 14, cost: 100, cooldown: 10,
      windup: 0.8, active: 0.1, recovery: 0.45,
      power: 3.9, damageType: 'magic', heavy: true, knockback: 6, stun: 0.5,
      applies: [{ status: 'burn', duration: 4, stacks: 3 }],
      projectile: { speed: 14, radius: 2.1, style: 'meteor' },
      anim: 'castBig', desc: 'Calls a meteor on the predicted enemy position.',
    },
  ],
  brute: [
    {
      id: 'hammer', name: 'Hammer Swing', slot: 'basic', kind: 'melee',
      range: 2.05, cost: 0, cooldown: 0.2,
      windup: 0.4, active: 0.12, recovery: 0.42,
      power: 1.4, damageType: 'physical', stagger: 0.38, knockback: 3.5, lunge: 0.35, hyperArmor: true,
      anim: 'slash', desc: 'Heavy swing with hyper armor.',
    },
    {
      id: 'ground_slam', name: 'Ground Slam', slot: 'skill', kind: 'projectile',
      range: 9, cost: 15, cooldown: 7,
      windup: 0.5, active: 0.1, recovery: 0.4,
      power: 1.5, damageType: 'physical', heavy: true, stun: 0.6, unblockable: true,
      projectile: { speed: 11, radius: 0.6, style: 'groundwave', ground: true },
      anim: 'slam', desc: 'Sends an unblockable shockwave along the ground.',
    },
    {
      id: 'war_cry', name: 'War Cry', slot: 'skill', kind: 'buff',
      range: 0, cost: 20, cooldown: 14,
      windup: 0.36, active: 0.1, recovery: 0.3,
      power: 0, damageType: 'physical', heal: 0.06,
      buff: [{ status: 'rage', duration: 6 }],
      anim: 'roar', desc: 'Enrage (+25% damage, +15% speed) and heal.',
    },
    {
      id: 'iron_skin', name: 'Iron Skin', slot: 'defense', kind: 'buff',
      range: 0, cost: 0, cooldown: 9,
      windup: 0.06, active: 0.06, recovery: 0.08,
      power: 0, damageType: 'physical',
      buff: [{ status: 'ironskin', duration: 2.4 }],
      anim: 'roar', desc: 'Harden: 50% damage reduction and unstoppable for 2.4s.',
    },
    {
      id: 'earthshatter', name: 'Earthshatter', slot: 'ultimate', kind: 'aoe',
      range: 3.3, cost: 100, cooldown: 10,
      windup: 0.6, active: 0.18, recovery: 0.75,
      power: 4.1, damageType: 'physical', heavy: true, unblockable: true, stun: 1.2, knockback: 6,
      lunge: 2.0, airborne: true, hyperArmor: true,
      anim: 'leap', desc: 'Leaping slam that shatters the ground. Unblockable, long stun.',
    },
  ],
};
